import type { DashboardData, Vulnerability } from "./types";

const oracleSummary =
  "Vulnerability in Oracle Platform Security for Java. Supported versions include 12.2.1.4.0 and 14.1.2.0.0. Network-based attacks may compromise confidentiality, integrity and availability.";

const inventoryAction =
  "Inventory affected products, verify exposure and follow the vendor remediation or mitigation guidance.";

function vulnerability(
  id: string,
  title: string,
  priorityScore: number,
  cvssScore: number,
  severity: Vulnerability["severity"],
  publishedAt: string,
  summary = oracleSummary,
  references: string[] = ["https://www.oracle.com/security-alerts/cpujul2026.html"],
): Vulnerability {
  return {
    id,
    title,
    summary,
    priorityScore,
    cvssScore,
    cvssVersion: cvssScore >= 9.2 ? "3.1 / 4.0" : "3.1",
    cvssVector: null,
    severity,
    epssScore: null,
    epssPercentile: null,
    cisaKev: false,
    knownExploited: false,
    knownRansomwareUse: false,
    sourceName: "NVD CVE API 2.0",
    sourceUrl: `https://nvd.nist.gov/vuln/detail/${id}`,
    publishedAt,
    products: [],
    references,
    reasons: [`CVSS ${cvssScore.toFixed(1)}`, "Official source", "Detection opportunity"],
    actions: [inventoryAction],
  };
}

export const FALLBACK_DATA: DashboardData = {
  schemaVersion: 1,
  project: "CyberDailyLog",
  generatedAt: "2026-07-23T08:43:46+00:00",
  coverageStart: "2026-07-22T08:43:40+00:00",
  coverageEnd: "2026-07-23T08:43:40+00:00",
  pipelineStatus: "operational",
  dataMode: "repository-snapshot",
  deliveryOrigin: "bundled-snapshot",
  deliveryChain: [
    {
      id: "github-raw",
      label: "GitHub Raw",
      role: "primary",
      status: "failed",
      url: "https://raw.githubusercontent.com/JimBLogic/CyberDailyLog/main/reports/latest.json",
    },
    {
      id: "jsdelivr-cdn",
      label: "jsDelivr CDN",
      role: "transport-backup",
      status: "failed",
      url: "https://cdn.jsdelivr.net/gh/JimBLogic/CyberDailyLog@main/reports/latest.json",
    },
    {
      id: "official-apis",
      label: "NVD + CISA KEV + FIRST EPSS",
      role: "official-backup",
      status: "failed",
      url: "https://nvd.nist.gov/developers/vulnerabilities",
    },
    {
      id: "bundled-snapshot",
      label: "Copia verificada incluida",
      role: "offline-fallback",
      status: "used",
      url: "https://github.com/JimBLogic/CyberDailyLog",
    },
  ],
  coverageConfidence: "low",
  coverageState: "insufficient",
  minimumPriority: 5,
  assessed: 298,
  aboveThreshold: 188,
  immediateAttentionCount: 0,
  immediateAttention:
    "No confirmed exploitation, CISA KEV or ransomware-linked item qualified.",
  distribution: [
    { key: "CRITICAL", label: "Critical", count: 13, color: "#c9342f" },
    { key: "HIGH", label: "High", count: 120, color: "#f27622" },
    { key: "MEDIUM", label: "Medium", count: 109, color: "#e7ad24" },
    { key: "LOW", label: "Low", count: 17, color: "#1747d1" },
    { key: "UNKNOWN", label: "Unknown", count: 35, color: "#8b8d91" },
  ],
  scoreBands: [
    { label: "0–2.4", count: 58, from: 0, to: 2.4 },
    { label: "2.5–4.9", count: 48, from: 2.5, to: 4.9 },
    { label: "5–7.4", count: 138, from: 5, to: 7.4 },
    { label: "7.5–8.9", count: 37, from: 7.5, to: 8.9 },
    { label: "9–10", count: 13, from: 9, to: 10 },
  ],
  vulnerabilities: [
    vulnerability(
      "CVE-2026-60372",
      "Oracle Platform Security for Java — centralized third-party jars",
      10,
      9.8,
      "CRITICAL",
      "2026-07-22T23:16:36.420000+00:00",
    ),
    vulnerability(
      "CVE-2026-60369",
      "Oracle Platform Security for Java — low-privileged network compromise",
      10,
      9.9,
      "CRITICAL",
      "2026-07-22T23:16:36.087000+00:00",
    ),
    vulnerability(
      "CVE-2026-60367",
      "Oracle Platform Security for Java — unauthenticated HTTP compromise",
      10,
      9.8,
      "CRITICAL",
      "2026-07-22T23:16:35.870000+00:00",
    ),
    vulnerability(
      "CVE-2026-60366",
      "Oracle Platform Security for Java — unauthenticated takeover",
      10,
      10,
      "CRITICAL",
      "2026-07-22T23:16:35.757000+00:00",
    ),
    vulnerability(
      "CVE-2026-13072",
      "MongoDB compute mode — BSON validation memory corruption",
      9.4,
      9.2,
      "CRITICAL",
      "2026-07-22T20:16:45.740000+00:00",
      "Insufficient validation of externally sourced BSON during aggregation pipeline processing can cause memory corruption. The affected compute-mode configuration is non-default.",
      ["https://jira.mongodb.org/browse/SERVER-128494"],
    ),
    vulnerability(
      "CVE-2026-64829",
      "Question2Answer — persistent session survives password reset",
      9.3,
      9.1,
      "CRITICAL",
      "2026-07-22T20:17:08.423000+00:00",
      "A previously obtained remember-me cookie can retain authenticated access because the forgot-password flow does not invalidate the persistent session.",
      ["https://github.com/q2a/question2answer/pull/1017"],
    ),
    vulnerability(
      "CVE-2026-16606",
      "Fujitsu openFT — unauthenticated remote code execution",
      9.1,
      9.3,
      "CRITICAL",
      "2026-07-22T16:17:16.800000+00:00",
      "Affected Fujitsu openFT versions on GNU/Linux and Oracle Solaris allow pre-authentication remote code execution.",
      ["https://security.eu.fsastech.com/"],
    ),
    vulnerability(
      "CVE-2026-2395",
      "Xpoda No Code Platform — SQL injection",
      9.1,
      9.8,
      "CRITICAL",
      "2026-07-22T15:16:54.193000+00:00",
      "Improper neutralization of SQL command elements in Xpoda No Code Platform allows SQL injection.",
      ["https://siberguvenlik.gov.tr/"],
    ),
  ],
  sourceHealth: [
    {
      source: "cisa_kev",
      label: "CISA KEV",
      status: "healthy",
      required: true,
      durationMs: 178,
      itemsReceived: 1653,
      itemsAccepted: 0,
      itemsRejected: 0,
      finishedAt: "2026-07-23T08:43:40.264784+00:00",
      error: null,
    },
    {
      source: "nvd",
      label: "NVD",
      status: "healthy",
      required: true,
      durationMs: 478,
      itemsReceived: 209,
      itemsAccepted: 209,
      itemsRejected: 0,
      finishedAt: "2026-07-23T08:43:40.743573+00:00",
      error: null,
    },
    {
      source: "github_advisories",
      label: "GitHub Advisories",
      status: "healthy",
      required: true,
      durationMs: 726,
      itemsReceived: 100,
      itemsAccepted: 100,
      itemsRejected: 0,
      finishedAt: "2026-07-23T08:43:41.470535+00:00",
      error: null,
    },
    {
      source: "rss_krebs",
      label: "Krebs on Security",
      status: "healthy",
      required: false,
      durationMs: 50,
      itemsReceived: 10,
      itemsAccepted: 0,
      itemsRejected: 0,
      finishedAt: "2026-07-23T08:43:41.520792+00:00",
      error: null,
    },
    {
      source: "rss_sans_isc",
      label: "SANS ISC",
      status: "healthy",
      required: false,
      durationMs: 293,
      itemsReceived: 10,
      itemsAccepted: 2,
      itemsRejected: 0,
      finishedAt: "2026-07-23T08:43:41.814660+00:00",
      error: null,
    },
    {
      source: "github_releases",
      label: "Defensive releases",
      status: "healthy",
      required: false,
      durationMs: 1340,
      itemsReceived: 90,
      itemsAccepted: 0,
      itemsRejected: 0,
      finishedAt: "2026-07-23T08:43:43.154919+00:00",
      error: null,
    },
    {
      source: "hacker_news",
      label: "Hacker News",
      status: "healthy",
      required: false,
      durationMs: 3344,
      itemsReceived: 40,
      itemsAccepted: 2,
      itemsRejected: 38,
      finishedAt: "2026-07-23T08:43:46.499446+00:00",
      error: null,
    },
    {
      source: "epss",
      label: "FIRST EPSS",
      status: "healthy",
      required: false,
      durationMs: 94,
      itemsReceived: 260,
      itemsAccepted: 29,
      itemsRejected: 231,
      finishedAt: "2026-07-23T08:43:46.594401+00:00",
      error: null,
    },
  ],
  history: [
    { date: "2026-07-16", assessed: 331, aboveThreshold: 247, immediateAttention: 0, critical: 34, high: 141, degraded: false },
    { date: "2026-07-17", assessed: 311, aboveThreshold: 233, immediateAttention: 0, critical: 33, high: 108, degraded: false },
    { date: "2026-07-18", assessed: 252, aboveThreshold: 185, immediateAttention: 0, critical: 24, high: 81, degraded: false },
    { date: "2026-07-19", assessed: 100, aboveThreshold: 59, immediateAttention: 0, critical: 5, high: 30, degraded: false },
    { date: "2026-07-20", assessed: 464, aboveThreshold: 9, immediateAttention: 0, critical: 1, high: 3, degraded: false },
    { date: "2026-07-21", assessed: 369, aboveThreshold: 254, immediateAttention: 0, critical: 30, high: 122, degraded: false },
    { date: "2026-07-22", assessed: 1562, aboveThreshold: 1276, immediateAttention: 0, critical: 269, high: 652, degraded: false },
    { date: "2026-07-23", assessed: 298, aboveThreshold: 188, immediateAttention: 0, critical: 13, high: 120, degraded: false },
  ],
  humanContext: {
    title: "ISC Stormcast for Thursday, July 23rd, 2026",
    sourceName: "SANS Internet Storm Center Handler's Diary",
    author: null,
    excerpt:
      "A bounded, publisher-provided excerpt from SANS ISC. Open the source for the complete analyst context.",
    sourceUrl: "https://isc.sans.edu/diary/rss/33178",
    publishedAt: "2026-07-23T02:00:03+00:00",
  },
  communityPulse: {
    title: "GigaToken: ~1000x faster language model tokenization",
    sourceName: "Hacker News",
    sourceUrl: "https://github.com/marcelroed/gigatoken/",
    discussionUrl: "https://news.ycombinator.com/item?id=49010167",
    score: 489,
    comments: 97,
    publishedAt: "2026-07-22T17:20:38+00:00",
    caveat: "Community interest signal; validate claims against primary sources.",
  },
  analystBriefs: [
    {
      title: "ISC Stormcast for Thursday, July 23rd, 2026",
      sourceName: "SANS Internet Storm Center Handler's Diary",
      author: null,
      excerpt:
        "A bounded, publisher-provided excerpt from SANS ISC. Open the source for the complete analyst context.",
      sourceUrl: "https://isc.sans.edu/diary/rss/33178",
      publishedAt: "2026-07-23T02:00:03+00:00",
    },
  ],
  communitySignals: [
    {
      title: "GigaToken: ~1000x faster language model tokenization",
      sourceName: "Hacker News",
      sourceUrl: "https://github.com/marcelroed/gigatoken/",
      discussionUrl: "https://news.ycombinator.com/item?id=49010167",
      score: 489,
      comments: 97,
      publishedAt: "2026-07-22T17:20:38+00:00",
      caveat:
        "Community interest signal; validate claims against primary sources.",
    },
  ],
  repositoryUrl: "https://github.com/JimBLogic/CyberDailyLog",
  reportUrl: "https://github.com/JimBLogic/CyberDailyLog/blob/main/reports/latest.md",
  lastFetchAt: "2026-07-23T08:43:46+00:00",
  nextRefreshAt: "2026-07-23T08:58:46+00:00",
  refreshIntervalMinutes: 15,
};
