#!/usr/bin/env bash
# fetch-news.sh – pulls free certs + top CVEs, creates daily markdown report,
# commits & pushes the change.

set -euo pipefail
IFS=$'\n\t'

# ----- CONFIG -----
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"
DATE=$(date +%F)
MD_PATH="cyber-intel-${DATE}.md"

# Static lists (replace with live API calls if you wish)
CERTS=(
  "Google Cloud Cybersecurity Certificate – free exam voucher (cloudskillsboost.google/paths/419)"
  "Cisco CBROPS – free 30 CE credits + exam coupon (GitHub Free-Certifications)"
  "AWS re/Start – free training + Cloud Practitioner voucher (GitHub Free-Certifications)"
  "Microsoft Azure Fundamentals (AZ-900) – free voucher AZFREE2025 (GitHub Free-Certifications)"
  "Palo Alto PCCET – free course discounted exam (paloaltonetworks.com)"
)

CVES=(
  "CVE-2025-30397 – Edge scripting engine memory corruption (CVSS 7.5) – patch Edge ASAP"
  "CVE-2025-32709 – WinSock driver elevation-of-privilege (CVSS 7.8) – update Windows"
  "CVE-2025-29813 – Azure DevOps Server privilege escalation (CVSS 10.0) – apply Azure patches"
)

# ----- PICK RANDOM 3 FROM EACH -----
SELECTED_CERTS=$(printf "%s\n" "${CERTS[@]}" | shuf -n3)
SELECTED_CVES=$(printf "%s\n" "${CVES[@]}" | shuf -n3)

# ----- BUILD MARKDOWN CONTENT -----
cat > "$MD_PATH" <<EOF
# Cyber Intelligence Report - ${DATE}

> Automated daily scan of free certifications and critical vulnerabilities

## 🎓 Free Cloud & Security Certifications

EOF

# Add certs numbered list
i=1
while IFS= read -r cert; do
    echo "${i}. ${cert}" >> "$MD_PATH"
    ((i++))
done <<< "$SELECTED_CERTS"

cat >> "$MD_PATH" <<EOF

## 🔴 Critical CVEs (CVSS ≥ 7.5)

EOF

# Add CVEs numbered list
i=1
while IFS= read -r cve; do
    echo "${i}. ${cve}" >> "$MD_PATH"
    ((i++))
done <<< "$SELECTED_CVES"

cat >> "$MD_PATH" <<EOF

---
*Last updated: $(date '+%Y-%m-%d %H:%M:%S')*  
*Generated by: fetch-news.sh*
EOF

# ----- COMMIT & PUSH -----
git add "$MD_PATH"
git commit -m "intel: daily cyber intelligence report (${DATE})"
git push

echo -e "\nCyber intelligence report created: ${MD_PATH}"
